### ISSUE TITLE
Live Fragment is not working

### ISSUE THREAD

**Issue by kethan** [Technical-Source/bruh#4]
@wlib Can you check please?

**Comment by kethan** [comment]
Ex: https://codesandbox.io/s/bruh-test-7lo6xt?file=/src/main.jsx

**Comment by wlib** [comment]
This actually looks like a bug - I'll update you when it's fixed.

**Comment by wlib** [comment]
Just so that you can fix this now (before a real fix is made), you can force the value to be an array like this:
```javascript
const ret = r([fallback]);
when.addReaction(() => {
  if (when.value) ret.value = children;
  else ret.value = [fallback];
});
```

**Comment by kethan** [comment]
Hmmm if I use the above one it works but breaks again if I use the nested one. Check for the update code on the same link.

**Comment by kethan** [comment]
Hi your code is amazing. I enjoyed understanding it. I have resolved the fragment issue but converting all nodes to array of fragments. I was about to make a pr but you solved in different way.

**Comment by kethan** [comment]
https://github.com/kethan/uele i have added more features like promise nodes, svg etc. I have few more things like to use any reactive library to process nodes.

**Comment by wlib** [comment]
> Hi your code is amazing. I enjoyed understanding it.

Thank you

> I have resolved the fragment issue but converting all nodes to array of fragments.

Just want to note that you no longer have to wrap it in an array, a reactive value can now switch between arrays and single values
